# Generated by Django 4.2.9 on 2024-03-19 16:10

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, null=True, populate_from="title"
            ),
        ),
    ]
